version: '3'

services:
  my-website:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html

  todo-app:
    image: docker/getting-started
    ports:
      - "8080:8080"